name: Docker

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build frontend
        run: |
          docker build -t ghcr.io/rdmfr/rdmarket-frontend:sha-${GITHUB_SHA::7} -t ghcr.io/rdmfr/rdmarket-frontend:edge ./frontend

      - name: Push frontend
        run: |
          docker push ghcr.io/rdmfr/rdmarket-frontend:sha-${GITHUB_SHA::7}
          docker push ghcr.io/rdmfr/rdmarket-frontend:edge

      - name: Build backend
        run: |
          docker build -t ghcr.io/rdmfr/rdmarket-backend:sha-${GITHUB_SHA::7} -t ghcr.io/rdmfr/rdmarket-backend:edge ./backend

      - name: Push backend
        run: |
          docker push ghcr.io/rdmfr/rdmarket-backend:sha-${GITHUB_SHA::7}
          docker push ghcr.io/rdmfr/rdmarket-backend:edge
